### ISSUE TITLE
Is the url for requesting tiktok signature changed?

### ISSUE THREAD

**Issue by arifrohmadi** [carcabot/tiktok-signature#107]
I have tried running the docker according to the tutorial then requested a signature tiktok using 
curl 
`curl -d "https://m.tiktok.com/share/item/list?secUid=&id=&type=5&count=30&minCursor=0&maxCursor=0&shareUid=" http://localhost:8080/signature`
the results obtained
`curl: (52) Empty reply from server`

Is the url for requesting tiktok signature changed?

**Comment by eliranmoyal** [comment]
try with t.tiktok.com

**Comment by arifrohmadi** [comment]
url for requesting tiktok signature still worked, just change the port to 8081 when running container
`docker run -p 8081:8081 -v $(pwd):/usr/app tiktok-signature`
thanks
