### ISSUE TITLE
TIKTOK HEADERS

### ISSUE THREAD

**Issue by Petr2282** [carcabot/tiktok-signature#137]
Guys please anyone who knows something about TikTok headers hTc6j8Njvn-a,b,c.... and their generation also with x-bogus and mstoken write me in telegram @cabaninst I can pay

**Comment by DeclanFrampton** [comment]
The headers following the 'hTc6j8Njvn' Format seem to be Shape Security's doing, good look trying to reverse their antibot, their scripts are virtualised afaik.

**Comment by Petr2282** [comment]
> The headers following the 'hTc6j8Njvn' Format seem to be Shape Security's doing, good look trying to reverse their antibot, their scripts are virtualised afaik.

Maybe you know any bypasses of that shape security?They have updated now

**Comment by DeclanFrampton** [comment]
> 

You're massively underestimating Shapes ability to prevent people reverse engineering their scripts. Sure its possible, but I've seen extremely high prices before offering 1 month API Access for $10,000. You're best off just closing this issue as its not an issue with the script, its an issue with your ability.
