### ISSUE TITLE
How to get SEC_UID

### ISSUE THREAD

**Issue by resatkrlc** [carcabot/tiktok-signature#150]
**Describe the bug**
Hello.
I tried to check this link:
https://t.tiktok.com/api/user/detail/?aid=1988&uniqueId=celal_samaa&language=it

as explained in comment section of https://github.com/carcabot/tiktok-signature/blob/87b0ee7f0440b29063e8da07ac01cc7e3d216192/examples/user-videos.js

but when i visit that link, i am getting:
`{"userInfo": {"user": {},"stats": {},"shareMeta": {}}}`

response.
How to get correct SEC_UID? thanks.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS : Windows
- NodeJs Version (node -v) : 17
- Signature Version : I dont know it
- CLI or Module : Module
- Do you run the tool through Proxy, VPN, VPS? No
- Preferably provide URL to the profile,hashtag,video and etc page

**Screenshots**

**Comment by resatkrlc** [comment]
Ah okay. I found it:

Just using this link 
https://www.tiktok.com/node/share/user/@celal_samaa?aid=1988  and i can extract the uid. It's working! Thanks anyway :)

**Comment by Huertas97** [comment]
> Ah okay. I found it:
> 
> Just using this link https://www.tiktok.com/node/share/user/@celal_samaa?aid=1988 and i can extract the uid. It's working! Thanks anyway :)

I've tried to use the new link but a 403 forbidden exception arise and no data is displayed in the browser when I use the new link proposed by @resatkrlc

**Comment by iTingle** [comment]
> > Ah okay. I found it:
> > Just using this link https://www.tiktok.com/node/share/user/@celal_samaa?aid=1988 and i can extract the uid. It's working! Thanks anyway :)
> 
> I've tried to use the new link but a 403 forbidden exception arise and no data is displayed in the browser when I use the new link proposed by @resatkrlc

the same trouble, if a 403 forbidden exception arise show, it means you current request ip is blocked by tiktok or in the tmp black list.

I got a method to fix it, but not sure it well longer.

1. send get method request of @resatkrlc 's url to get cookie,the important is msToken;
2. url splicing msToken, and set cookie last request, send request again, it well be ok;

do you have any other idea?

**Comment by resatkrlc** [comment]
@iTingle @Huertas97  sorry for late response. Before months it was working but i am out of tiktok project nowadays. i can start to investing again, but i think tiktok sends some other cookies or something in user page. check a profile, and check network at the same time.
