### ISSUE TITLE
Page.evaluate syntax error

### ISSUE THREAD

**Issue by NickParks** [carcabot/tiktok-signature#158]
**Describe the bug**
When following the [user-info example](https://github.com/carcabot/tiktok-signature/blob/master/examples/user-info.js) an error is thrown.

**To Reproduce**
- Clone repo
- Docker build
- Docker run
- Run example code in user-info.js

**Screenshots**
<img width="797" alt="Screen Shot 2022-08-12 at 11 21 55 AM" src="https://user-images.githubusercontent.com/5506537/184420398-16ac3b89-c06e-45a8-b57f-80d88270f1df.png">

**Comment by pthieu** [comment]
On successful request using the this example, I'm getting an empty response
```
{statusCode: 0,body: {userData: {},statusCode: -1,shareUser: {}}} 
```

**Comment by pthieu** [comment]
@fojia does your user info code still work for your implementation? Looks like the example from the PR you put in on Jun 29th (#152) is no longer working.

**Comment by pykereaper** [comment]
I'm having the same problem. Using the example, I only get the same response as @pthieu :
```
{statusCode: 0,body: {userData: {},statusCode: -1,shareUser: {}}} 
```

**Comment by fojia** [comment]
@pthieu 
yes, it was working until today.

**Comment by fojia** [comment]
@pykereaper @pthieu
Updated example and made the PR. Now it works.
