### ISSUE TITLE
No User information using "user-info.js"

### ISSUE THREAD

**Issue by Huertas97** [carcabot/tiktok-signature#164]
**Describe the bug**
When I install `tiktok-signature`, clone the repository, and run `examples/user-info.js` file, I obtain this result:

```shell
 $node ".\tiktok-signature\examples\user-info.js"
```

```
{
    statusCode: -1,
    userInfo: {}
}
```

If have tested it with different usernames: therock, taylorswift. And it returns the same. 

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- OS: Windows 10
- NodeJs Version: v18.12.0
- Signature Version
- CLI or Module: Module
- Do you run the tool through Proxy, VPN, VPS? --> No. Localhost
- Preferably provide URL to the profile,hashtag,video and etc page: [therock](https://www.tiktok.com/@therock) [taylorswift](https://www.tiktok.com/@taylorswift)

**Comment by cteam8730-source** [comment]
MS4wLjABAAAAbvQPRnHIP4vrXwzRAzp7MklMLgxpi0zVMqEx9tEojJ-ohYGA9i_ClGB4opkZhc6y
 
Family target fake account TikTok
