### ISSUE TITLE
get posts not work in US

### ISSUE THREAD

**Issue by callMeMakerRen** [carcabot/tiktok-signature#172]
**Describe the bug**
get posts not work in us, get empty response with status 200

i am not sure if tiktok add addition check for US user access,i do notice that the us tiktok use domain `us.tiktok.com`,and the link not work for about 2hours ,not sure if it is because mstoken expired. and the `www.tiktok.com` api is not usable too.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS Mac
- NodeJs Version (node -v) v18.7.0
- Signature Version 
- CLI or Module cli
- Do you run the tool through Proxy, VPN, VPS? Proxy
- Preferably provide URL to the profile,hashtag,video and etc page 

**Screenshots**

**Comment by PATAPOsha** [comment]
did you solve issue?
