### ISSUE TITLE
How to get msToken

### ISSUE THREAD

**Issue by TWS615** [carcabot/tiktok-signature#184]
I had the the trending.py and It does not return any data. I found that msToken is required to get the data. Is it possible to add the msToken to the signed_url?

**Comment by HH7H** [comment]
> I had the the trending.py and It does not return any data. I found that msToken is required to get the data. Is it possible to add the msToken to the signed_url?

what's the TikTok URL you  want to sign

**Comment by YoussefElshemi** [comment]
> > I had the the trending.py and It does not return any data. I found that msToken is required to get the data. Is it possible to add the msToken to the signed_url?
> 
> what's the TikTok URL you want to sign

Hi, do you mind sharing your discord or something? I have a few questions that you might be able to help me with.

**Comment by HH7H** [comment]
> > > I had the the trending.py and It does not return any data. I found that msToken is required to get the data. Is it possible to add the msToken to the signed_url?
> > 
> > 
> > what's the TikTok URL you want to sign
> 
> Hi, do you mind sharing your discord or something? I have a few questions that you might be able to help me with.

My Telegram: @NkNkER

**Comment by Roman-Kasianenko** [comment]
> I had the the trending.py and It does not return any data. I found that msToken is required to get the data. Is it possible to add the msToken to the signed_url?

@TWS615 , doest it work if you have `msToken`? I have tried to add `msToken` as URL parameter but it doesn't work anyway :(

**Comment by tonywangcn** [comment]
@Roman-Kasianenko @YoussefElshemi Hi did you make it?
