### ISSUE TITLE
Retrieving `secUid`?

### ISSUE THREAD

**Issue by masonwrolstad** [carcabot/tiktok-signature#187]
Hello there! 

From the `user-info.js` there's a reference to being able to get user info via this endpoint: https://t.tiktok.com/api/user/detail/?aid=1988&uniqueId=username&language=it

But it apparently isn't working anymore. Does anyone else know if there's another endpoint to hit to retrieve the user `secUid`?

It looks like the challenge endpoint (https://t.tiktok.com/api/challenge/detail/?challengeName=petsoftiktok) still works. 

Thanks for all the help!

**Comment by ach206** [comment]
bump

**Comment by sbsto** [comment]
I'm having the same issue (can't get user info):

**Description**
user-info.js example times out with any username. All other examples work well. 

**To Reproduce**
Steps to reproduce the behavior:

- Linux (Ubuntu 22.04)
- NodeJs Version 18.13.0
- Signature Version 1.8.0
- Module
- No proxy, VPN, or VPS.
- Doesn't work on any URL / username.
- Run `node examples/user-info.js`

**Comment by Spawnrad** [comment]
Got exactly the same issue u can't get the user feed.
