### ISSUE TITLE
`user-info.js` example times out 

### ISSUE THREAD

**Issue by sbsto** [carcabot/tiktok-signature#190]
**Describe the bug**
`user-info.js` example times out with any username. All other examples work well. I'm not sure if I'm doing something wrong, or how to troubleshoot this. Could it be something to do with the `TT_REQ_PERM_URL`? I appreciate any help you guys can give!

**To Reproduce**
- Linux (Ubuntu 22.04)
- NodeJs Version 18.13.0
- Signature Version 1.8.0
- Module
- No proxy, VPN, or VPS. 
- Doesn't work on any URL / username.
- Run `node examples/user-info.js`

**Comment by sbsto** [comment]
Just realised this is basically a duplicate of #187. Closing this issue.

**Comment by llhhyhh** [comment]
Excuse me, have you solved your problem, how did you solve it, is it convenient for you to share it, thank you
