### ISSUE TITLE
Normal search example

### ISSUE THREAD

**Issue by schneckentempo** [carcabot/tiktok-signature#195]
First of all I am not very familiar with tiktok itself, but I need to place a search (like on the landing page) and paginate through it. Is it possible to use this package to request a normal search? I played around a bit but the best I could get was a response which said I have to login first.

I tried to use this endpoint: `https://www.tiktok.com/api/search/item/full`
Also found the api endpoint `https://www.tiktok.com/api/search/general/full` when logged in but same outcome

If it is possible can you provide an example?

Best regards

**Comment by mario-lemes** [comment]
Hi all, also looking for a solution for that specific API. 

Any advise in order to move forward?

Thanks
