### ISSUE TITLE
python support 

### ISSUE THREAD

**Issue by sheldygg** [carcabot/tiktok-signature#197]
go together rewrite index.js to python

**Comment by sheldygg** [comment]
recently i did that https://pastebin.com/F20hDrnz
but its raise exception 70 line with this traceback
https://pastebin.com/SqnkJrC9

**Comment by sheldygg** [comment]
now i made that
https://github.com/sheldygg/tiktok-signature
signature generated successfully but when i make request to tt api returns nothing.
maybe someone know, why?

**Comment by sheldygg** [comment]
finally solved
https://github.com/sheldygg/tiktok-signature

**Comment by Superheroff** [comment]
> finally solved https://github.com/sheldygg/tiktok-signature

/api/post/item_list/无法使用
