### ISSUE TITLE
Fetch user info returns empty info

### ISSUE THREAD

**Issue by moonspirit** [carcabot/tiktok-signature#204]
**Describe the bug**
In the example, to fetch a tiktok unique user id (e.g.: rihanna), the script return only

```
{ status_code: 0 }
```
without any useful information.

Other apis like user-videos/comments works fine for me, Thanks for your great work!

**Comment by mzaryabuddin1** [comment]
i am also recieving the same issue while i am scrapping user-info it return { status_code: 0 }

**Comment by Jhonatas-Matheus** [comment]
How did you solve this problem? Could you share it with you? I have the same problem.
