### ISSUE TITLE
Fail to get SEC_UID

### ISSUE THREAD

**Issue by developeralim** [carcabot/tiktok-signature#207]
Please help me.  i am trying to get secUid by this URL https://t.tiktok.com/api/user/detail/?aid=1988&uniqueId=username&language=it. but it gives me nothing in api request.

**Comment by jcgohr** [comment]
What is secUid? I am also having problems but not the same one and Im wondering if we can work together

**Comment by levymoreira** [comment]
If you guys can, create a small repository on github with an example of the problem, I'm using the signature here and it's working fine for my urls.

**Comment by jcgohr** [comment]
@levymoreira Are you using the basic example provided in the examples folder.

**Comment by jcgohr** [comment]
The example for [list_items](https://github.com/carcabot/tiktok-signature/blob/master/examples/user-videos.js) is not working for me and this is the one I need. The example doesn't work (no data) but when I copy the fetch request from the browser it works as intended but only for a few minutes.

**Comment by zakrian07** [comment]
are you using proxy?

**Comment by jcgohr** [comment]
no but it works on with requests generated from real browsers
