### ISSUE TITLE
Signing POST request

### ISSUE THREAD

**Issue by dhanh** [carcabot/tiktok-signature#71]
Hello, 

I tried to use your code to sign a POST request but it not work. It seem that the request's body also need to be sign instead of just url. Would you implement signing function for POST request also? Or just point me how to sign it?

Thanks in advanced

**Comment by acrogenesis** [comment]
@dhanh which POST are you trying to sign? I haven't seen any POST on the web API.

**Comment by dhanh** [comment]
> @dhanh which POST are you trying to sign? I haven't seen any POST on the web API.

@acrogenesis Hi, I wanna submit Login form, it contains email/username and password.

**Comment by acrogenesis** [comment]
@dhanh I believe that's out of scope for this project but here you can see the encryption algorithm for the email/username and password https://github.com/szdc/tiktok-api/blob/master/src/cryptography.ts

**Comment by dhanh** [comment]
@acrogenesis  Thank you, I'll try to find it myself.

**Comment by acrogenesis** [comment]
@dhanh that link is the algorithm to encrypt the user and password
